# Generated by Django 6.0 on 2025-12-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('casual', 'Casual (Non-Competitive / Just for Fun)'), ('showcase', 'Showcase (Exhibitions, Photoshoots, No Judging)'), ('novice', 'Novice (0–1 Competitive Awards)'), ('journeyman', 'Journeyman (2–3 Competitive Awards)'), ('master', 'Master (4+ Awards / Professional / International)')], default='casual', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
