# Generated by Django 6.0 on 2025-12-31 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_cosplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('journal', 'Journal Entry'), ('status', 'Status Update')], default='journal', max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='progress/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cosplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='community.cosplay')),
            ],
        ),
    ]
