# Generated by Django 6.0 on 2026-01-03 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_progressupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosplayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cosplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='community.cosplay')),
            ],
        ),
        migrations.CreateModel(
            name='CosplayEntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cosplay_entries/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.cosplayentry')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgressUpdate',
        ),
    ]
