# Generated by Django 6.0 on 2026-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
