# Generated by Django 6.0 on 2026-01-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_eventpost_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
